# -*- coding: utf-8 -*-
"""
历史单据回填(V4 方案 §8)。幂等,可重复执行。

1. 扫描 output/ 下本系统生成的 quotation_*.xlsx / pi_*.xlsx:
   结构化解析(客户/联系人/报价人/日期/编号/明细),成功 -> 完整入档(可转 PI);
   解析失败 -> archived_only。
2. 扫描 config.legacy_dirs(D:\\报价\\PI 等)下的 pi_* / quotation_* PDF/xlsx:
   全部 archived_only 入档,legacy_file 记绝对路径(只引用,不复制)。
   文件名变体(退税修改版 / (1) / P1..)容错;同号多文件按日期序分配 revision。
3. next_seq 三方核对(output + legacy + 索引),不足自动修正。

用法:  python tools/migrate_backfill.py
"""
import os, sys, re, json, datetime

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE)
from engine.docstore import DocStore, DuplicateKeyError  # noqa: E402
from openpyxl import load_workbook  # noqa: E402

DATA = os.path.join(BASE, "data")
OUTPUT = os.path.join(BASE, "output")


def load_config():
    with open(os.path.join(DATA, "config.json"), "r", encoding="utf-8") as f:
        return json.load(f)


def save_config(config):
    import shutil
    p = os.path.join(DATA, "config.json")
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    shutil.copy2(p, p + ".bak_migrate_" + ts)
    tmp = p + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(config, f, ensure_ascii=False, indent=1)
    os.replace(tmp, p)


def file_mtime_iso(path):
    ts = datetime.datetime.fromtimestamp(os.path.getmtime(path)).astimezone()
    return ts.isoformat(timespec="seconds")


def parse_own_quotation(path):
    """Parse a quotation xlsx generated by quote_engine. Returns doc fields
    (without no/date meta merge) or None on any surprise."""
    try:
        wb = load_workbook(path, data_only=False)
        ws = wb.active
        head_f = str(ws.cell(10, 6).value or "")
        tiered = "Band" in head_f
        if str(ws.cell(10, 1).value or "") != "No.":
            return None
        items = []
        r = 11
        while r < 200:
            c1 = ws.cell(r, 1).value
            if c1 is None or not str(c1).strip().isdigit():
                break
            item = {
                "item": ws.cell(r, 2).value or "",
                "desc": ws.cell(r, 4).value or "",
                "unit": ws.cell(r, 5).value or "PCS",
                "image": "",
            }
            if tiered:
                item.update({
                    "band1": ws.cell(r, 6).value, "price1": _numval(ws.cell(r, 7).value),
                    "band2": ws.cell(r, 8).value, "price2": _numval(ws.cell(r, 9).value),
                })
            else:
                item.update({
                    "qty": _numval(ws.cell(r, 6).value),
                    "unit_price": _numval(ws.cell(r, 7).value),
                })
            items.append(item)
            r += 1
        if not items:
            return None
        total = None
        if not tiered:
            total = 0.0
            for it in items:
                if it.get("qty") is not None and it.get("unit_price") is not None:
                    total += it["qty"] * it["unit_price"]
            total = round(total, 2)
        return {
            "customer": ws["B6"].value or "", "contact": ws["B7"].value or "",
            "from_name": ws["G6"].value or "", "date": ws["G7"].value or "",
            "no": ws["G8"].value or "",
            "mode": "tiered" if tiered else "standard",
            "items": items,
            "totals": {"amount": total, "amount_words": None},
        }
    except Exception:
        return None


def _numval(v):
    if v in (None, ""):
        return None
    try:
        f = float(v)
        return int(f) if f == int(f) else f
    except (ValueError, TypeError):
        return None


def next_free_rev(index_entries, no, doc_type):
    revs = [int(e.get("revision", 0)) for e in index_entries
            if e["no"] == no and e["doc_type"] == doc_type]
    return (max(revs) + 1) if revs else 0


def main():
    config = load_config()
    prefix = config.get("pi", {}).get("prefix", "XNY-AD")
    ds = DocStore(DATA)
    idx = ds.load_index()["entries"]
    known_files = {e.get("file") for e in idx if e.get("file")}
    known_legacy = {e.get("legacy_file") for e in idx if e.get("legacy_file")}
    structured_keys = {(e["no"], e["doc_type"], str(e.get("date", "")))
                       for e in idx if not e.get("archived_only")}

    n_parsed = n_arch = n_skip = 0
    max_seen = 0
    num_pat = re.compile(re.escape(prefix) + r"(\d+)")

    def bump_max(no):
        nonlocal max_seen
        m = num_pat.search(str(no))
        if m:
            max_seen = max(max_seen, int(m.group(1)))

    # ---- 1) own output/ files ----
    own_pat = re.compile(r"^(quotation|pi)_(\d{8})_(.+?)(?:-R(\d+))?\.xlsx$")
    for name in sorted(os.listdir(OUTPUT)):
        m = own_pat.match(name)
        if not m:
            continue
        doc_type, date8, no, rev_s = m.group(1), m.group(2), m.group(3), m.group(4)
        relfile = f"output/{name}"
        bump_max(no)
        if relfile in known_files:
            n_skip += 1
            continue
        rev = int(rev_s) if rev_s else 0
        if ds.exists(no, doc_type, rev):
            n_skip += 1
            continue
        date_disp = f"{date8[:4]}/{date8[4:6]}/{date8[6:8]}"
        parsed = parse_own_quotation(os.path.join(OUTPUT, name)) if doc_type == "quotation" else None
        if parsed and parsed.get("no"):
            doc = {
                "no": parsed["no"] or no, "doc_type": doc_type, "revision": rev,
                "source": None, "date": parsed["date"] or date_disp,
                "from_name": parsed["from_name"], "currency": "USD",
                "customer": parsed["customer"], "contact": parsed["contact"],
                "mode": parsed["mode"], "items": parsed["items"],
                "terms": {}, "totals": parsed["totals"],
                "file": relfile, "legacy_file": None, "archived_only": False,
                "created_at": file_mtime_iso(os.path.join(OUTPUT, name)),
                "note": "migrated:parsed",
            }
            label = "解析入档"
            n_parsed += 1
        else:
            doc = {
                "no": no, "doc_type": doc_type, "revision": rev,
                "source": None, "date": date_disp, "from_name": "", "currency": "",
                "customer": "", "contact": "", "items": [],
                "terms": {}, "totals": {"amount": None, "amount_words": None},
                "file": relfile, "legacy_file": None, "archived_only": True,
                "created_at": file_mtime_iso(os.path.join(OUTPUT, name)),
                "note": "migrated:archived_only",
            }
            label = "存档(无明细)"
            n_arch += 1
        try:
            ds.save_document(doc)
            idx.append(ds.index_entry(doc))
            if not doc["archived_only"]:
                structured_keys.add((doc["no"], doc_type, str(doc["date"])))
            print(f"  [{label}] {name}")
        except DuplicateKeyError:
            n_skip += 1

    # ---- 2) legacy dirs ----
    legacy_pat = re.compile(
        r"^(pi|quotation)_+(\d{8})_(" + re.escape(prefix) + r"\d+)(.*)\.(pdf|xlsx)$", re.I)
    groups = {}  # (no, doc_type, date8, variant) -> [paths]
    for d in config.get("legacy_dirs", []):
        if not os.path.isdir(d):
            print(f"  [跳过] 目录不存在: {d}")
            continue
        for name in sorted(os.listdir(d)):
            m = legacy_pat.match(name)
            if not m:
                continue
            doc_type, date8, no, variant = m.group(1).lower(), m.group(2), m.group(3), m.group(4).strip()
            bump_max(no)
            groups.setdefault((no, doc_type, date8, variant), []).append(os.path.join(d, name))

    for (no, doc_type, date8, variant), paths in sorted(groups.items()):
        # same no+date+variant in pdf and xlsx = the same document; prefer pdf
        paths.sort(key=lambda p: (not p.lower().endswith(".pdf"), p))
        main_file = paths[0]
        if any(p in known_legacy for p in paths):
            n_skip += 1
            continue
        date_disp = f"{date8[:4]}/{date8[4:6]}/{date8[6:8]}"
        if (no, doc_type, date_disp) in structured_keys:
            print(f"  [跳过] {os.path.basename(main_file)} (已有同号同日结构化档案)")
            n_skip += 1
            continue
        rev = next_free_rev(idx, no, doc_type)
        doc = {
            "no": no, "doc_type": doc_type, "revision": rev,
            "source": None, "date": date_disp, "from_name": "", "currency": "",
            "customer": "", "contact": "", "items": [],
            "terms": {}, "totals": {"amount": None, "amount_words": None},
            "file": None, "legacy_file": main_file, "archived_only": True,
            "created_at": file_mtime_iso(main_file),
            "note": ("legacy" + (f" 变体:{variant}" if variant else "")
                     + (f" 另有:{os.path.basename(paths[1])}" if len(paths) > 1 else "")),
        }
        try:
            ds.save_document(doc)
            idx.append(ds.index_entry(doc))
            tag = f" r{rev}" if rev else ""
            print(f"  [旧档入索引{tag}] {os.path.basename(main_file)}")
            n_arch += 1
        except DuplicateKeyError:
            n_skip += 1

    # ---- 3) next_seq check ----
    configured = int(config.get("pi", {}).get("next_seq") or 1)
    fixed = ""
    if configured <= max_seen:
        config["pi"]["next_seq"] = max_seen + 1
        save_config(config)
        fixed = f"(原 {configured} 偏小,已自动修正)"

    print()
    print("========== 迁移报告 ==========")
    print(f"结构化解析入档: {n_parsed} 条")
    print(f"仅存档(无明细): {n_arch} 条")
    print(f"跳过(已入档/重复): {n_skip} 条")
    print(f"已见最大编号: {prefix}{max_seen}")
    print(f"next_seq: {config['pi']['next_seq']} {fixed}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    main()
